# Generated by Django 4.1.4 on 2023-02-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='images/product/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категория товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, verbose_name='Товар')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/product/', verbose_name='Фото')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('memory', models.CharField(max_length=30, verbose_name='Оперативная память')),
                ('cpu', models.CharField(max_length=30, verbose_name='ЦПУ')),
                ('screen', models.CharField(max_length=30, verbose_name='Размер экрана')),
                ('orders', models.IntegerField(default=0, verbose_name='Покупок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
